import { type Challenge } from './db';

export const initialChallenges: Challenge[] = [
 
  // SYSTEM & BACKEND
  { title: "Thundering Herd", category: "System", subTopic: "Caching", system: "Redis / DB", symptom: "DB CPU spikes to 100% every hour exactly.", chaosFactor: "Keys expiring simultaneously without jitter.", solutionClues: ["Jitter TTL", "Cache Stampede protection"], level: "Senior" },
  { title: "Ghost Writes", category: "System", subTopic: "Event Sourcing", system: "Event Store", symptom: "Balance mismatch in ledger projections.", chaosFactor: "Worker crashed before checkpointing.", solutionClues: ["Idempotency", "Two-phase commit"], level: "Senior" },
  { title: "Zombie TCP", category: "System", subTopic: "Networking", system: "Linux Server", symptom: "Max connections reached with 0 users.", chaosFactor: "No TCP Keep-Alive on half-open sockets.", solutionClues: ["Keep-alive", "Idle timeouts"], level: "Senior" },
  { title: "Split Brain", category: "System", subTopic: "Consensus", system: "Etcd Cluster", symptom: "Two nodes acting as Leader.", chaosFactor: "Network partition with N/2 quorum logic.", solutionClues: ["N/2 + 1 Quorum", "Fencing tokens"], level: "Senior" },
  { title: "Out-of-Order", category: "System", subTopic: "Kafka", system: "Message Bus", symptom: "Delete processed before Create.", chaosFactor: "Events sent to different partitions.", solutionClues: ["Consistent hashing", "Partition keys"], level: "Senior" },
  { title: "Write Amplification", category: "System", subTopic: "Storage", system: "SSD / NoSQL", symptom: "Latency spikes during high write volume.", chaosFactor: "LSM Tree compaction lagging.", solutionClues: ["Compaction strategy", "Throttling"], level: "Senior" },
  { title: "Hot Shard", category: "System", subTopic: "NoSQL", system: "DynamoDB", symptom: "429 Throttling despite low total throughput.", chaosFactor: "One partition key receiving 90% of traffic.", solutionClues: ["Key salting", "Shard splitting"], level: "Senior" },
  { title: "Deadlock", category: "System", subTopic: "RDBMS", system: "Postgres", symptom: "Transaction timeouts under load.", chaosFactor: "Circular lock dependency on row updates.", solutionClues: ["Ordered locking", "Retry logic"], level: "Senior" },
  { title: "Connection Leak", category: "System", subTopic: "App Server", system: "Node/Java", symptom: "Memory grows until OOM.", chaosFactor: "HTTP client not closing response streams.", solutionClues: ["Finalizers", "Connection pooling"], level: "Senior" },
  { title: "Serializing Bloat", category: "System", subTopic: "API", system: "REST/gRPC", symptom: "Payloads are 10x larger than expected.", chaosFactor: "Circular references in JSON stringify.", solutionClues: ["DTO mapping", "Schema validation"], level: "Senior" },

  //   // FRONTEND
  { title: "Memory Leak", category: "Frontend", subTopic: "React", system: "Browser", symptom: "Tab crashes after 1 hour.", chaosFactor: "setInterval in useEffect without cleanup.", solutionClues: ["Effect cleanup", "WeakMap"], level: "Senior" },
  { title: "Layout Shift", category: "Frontend", subTopic: "CSS", system: "Core Vitals", symptom: "High CLS score on slow 3G.", chaosFactor: "Web fonts reflowing text on load.", solutionClues: ["font-display: swap", "Preload"], level: "Senior" },
  { title: "Infinite Render", category: "Frontend", subTopic: "React", system: "UI Thread", symptom: "UI is sluggish; profiler shows 500 renders/sec.", chaosFactor: "Passing object literals as props to memo().", solutionClues: ["useMemo", "useCallback"], level: "Senior" },
  { title: "Hydration Mismatch", category: "Frontend", subTopic: "Next.js", system: "SSR", symptom: "UI flashes/changes after load.", chaosFactor: "Using window.innerWidth in initial render.", solutionClues: ["useLayoutEffect", "Client-only check"], level: "Senior" },
  { title: "Stale Closure", category: "Frontend", subTopic: "JS", system: "Logic", symptom: "Event listener uses old variable value.", chaosFactor: "Listener captured stale state in scope.", solutionClues: ["useRef", "Dependency arrays"], level: "Senior" },
  { title: "Z-Index War", category: "Frontend", subTopic: "CSS", system: "Styles", symptom: "Modal appears behind the header.", chaosFactor: "Nested stacking contexts via transform.", solutionClues: ["Portals", "Isolation: isolate"], level: "Senior" },
  { title: "Race Condition", category: "Frontend", subTopic: "Fetch", system: "Data", symptom: "Wrong data displayed after fast clicking.", chaosFactor: "Earlier fetch returned after later fetch.", solutionClues: ["AbortController", "SwitchMap"], level: "Senior" },
  { title: "Bundle Bloat", category: "Frontend", subTopic: "Build", system: "Vite/Webpack", symptom: "First load is 5MB.", chaosFactor: "Importing entire lodash instead of sub-modules.", solutionClues: ["Tree shaking", "Code splitting"], level: "Senior" },
  { title: "Prop Drilling", category: "Frontend", subTopic: "Architecture", system: "React State", symptom: "Refactoring one component breaks 5 others.", chaosFactor: "State passed through 10 layers of components.", solutionClues: ["Context API", "Zustand/Redux"], level: "Senior" },
  { title: "Passive Listeners", category: "Frontend", subTopic: "Mobile", system: "Scrolling", symptom: "Jank when scrolling on touch devices.", chaosFactor: "Non-passive scroll listeners blocking thread.", solutionClues: ["{ passive: true }"], level: "Senior" },

  //   // SECURITY
  { title: "IDOR", category: "Security", subTopic: "Auth", system: "API", symptom: "User A can see User B data via URL change.", chaosFactor: "Checking session but not resource ownership.", solutionClues: ["Ownership check", "UUIDs"], level: "Senior" },
  { title: "XSS Injection", category: "Security", subTopic: "Input", system: "UI", symptom: "Session hijacked via comments.", chaosFactor: "dangerouslySetInnerHTML used without DOMPurify.", solutionClues: ["Sanitization", "CSP headers"], level: "Senior" },
  { title: "JWT Alg None", category: "Security", subTopic: "Tokens", system: "Auth Service", symptom: "Fake tokens being accepted as valid.", chaosFactor: "Backend allows 'none' algorithm in header.", solutionClues: ["Alg verification", "Secret rotation"], level: "Senior" },
  { title: "Rate Limit Bypass", category: "Security", subTopic: "Traffic", system: "Gateway", symptom: "Brute force works despite limits.", chaosFactor: "Tracking by IP while attacker uses proxies.", solutionClues: ["User ID limits", "WAF"], level: "Senior" },
  { title: "Secret Leak", category: "Security", subTopic: "CI/CD", system: "GitHub", symptom: "Unauthorized AWS spending.", chaosFactor: "IAM keys hardcoded in public repo.", solutionClues: ["Env vars", "Secret scanning"], level: "Senior" },
  { title: "CORS Misconfig", category: "Security", subTopic: "Browser", system: "API", symptom: "Preflight failure in production.", chaosFactor: "Allowing '*' with credentials enabled.", solutionClues: ["Explicit origin", "Credentials: false"], level: "Senior" },
  { title: "SQLi", category: "Security", subTopic: "Database", system: "Backend", symptom: "Data dumped via search bar.", chaosFactor: "String concatenation used in raw SQL queries.", solutionClues: ["Parameterized queries", "ORM"], level: "Senior" },
  { title: "Replay Attack", category: "Security", subTopic: "Network", system: "API", symptom: "Payment processed twice with same signature.", chaosFactor: "Missing nonce or timestamp validation.", solutionClues: ["Nonces", "Idempotency keys"], level: "Senior" },
  { title: "Dependency Vulnerability", category: "Security", subTopic: "Supply Chain", system: "npm", symptom: "Malicious code found in node_modules.", chaosFactor: "Using outdated packages with known CVEs.", solutionClues: ["npm audit", "Snyk"], level: "Senior" },
  { title: "Open Redirect", category: "Security", subTopic: "Navigation", system: "Web", symptom: "Users phished via your domain.", chaosFactor: "Redirecting to unvalidated 'returnTo' URL param.", solutionClues: ["Allowlist URLs", "Internal paths only"], level: "Senior" },

//   // DEVOPS
  { title: "OOM Kill Loop", category: "DevOps", subTopic: "Kubernetes", system: "Pod", symptom: "Exit Code 137 every 2 minutes.", chaosFactor: "Container limit lower than memory request.", solutionClues: ["Profiling", "Resource limits"], level: "Senior" },
  { title: "Cold Start", category: "DevOps", subTopic: "Serverless", system: "Lambda", symptom: "8s latency on first request.", chaosFactor: "Heavy DB init inside the handler function.", solutionClues: ["Global scope init", "Lean runtimes"], level: "Senior" },
  { title: "Disk Saturation", category: "DevOps", subTopic: "OS", system: "EC2", symptom: "Server stops accepting writes.", chaosFactor: "Logrotate disabled; debug logs filled disk.", solutionClues: ["Logrotate", "Central logging"], level: "Senior" },
  { title: "Deployment Deadlock", category: "DevOps", subTopic: "K8s", system: "Rollout", symptom: "Rolling update stuck at 1/3 pods.", chaosFactor: "Readiness probe failing on new version.", solutionClues: ["Probe tuning", "Rollback"], level: "Senior" },
  { title: "Artifact Poisoning", category: "DevOps", subTopic: "Docker", system: "Registry", symptom: "Production running 'latest' but it's old code.", chaosFactor: "Using 'latest' tag instead of immutable hashes.", solutionClues: ["Image digests", "Tagging strategy"], level: "Senior" },
  { title: "Ingress Flapping", category: "DevOps", subTopic: "Network", system: "Load Balancer", symptom: "Intermittent 502 Errors.", chaosFactor: "Keep-alive timeout mismatch between LB and App.", solutionClues: ["Timeout alignment"], level: "Senior" },
  { title: "Config Drift", category: "DevOps", subTopic: "Terraform", system: "Infra", symptom: "Manual change reverted by CI/CD.", chaosFactor: "Changes made via UI instead of code.", solutionClues: ["GitOps", "Terraform plan"], level: "Senior" },
  { title: "Zombie Instances", category: "DevOps", subTopic: "Cloud", system: "AWS", symptom: "Bill rising but traffic is flat.", chaosFactor: "Orphaned EBS volumes from deleted EC2s.", solutionClues: ["Cost Explorer", "Auto-cleanup"], level: "Senior" },
  { title: "Heisenbug Logs", category: "DevOps", subTopic: "Logging", system: "ELK", symptom: "Log messages missing during high load.", chaosFactor: "UDP syslog dropping packets under pressure.", solutionClues: ["TCP logging", "Backpressure"], level: "Senior" },
  { title: "IAM Over-permission", category: "DevOps", subTopic: "Security", system: "Cloud", symptom: "Compromised pod deleted the S3 bucket.", chaosFactor: "EC2 Role had 'AdministratorAccess' policy.", solutionClues: ["Least Privilege", "IAM Roles for Pods"], level: "Senior" },

//   // AI & DATA
  { title: "Token Overflow", category: "AI", subTopic: "LLM", system: "GPT-4", symptom: "Chatbot cuts off mid-sentence.", chaosFactor: "Context window exceeded on long docs.", solutionClues: ["Chunking", "Summarization"], level: "Senior" },
  { title: "Model Drift", category: "AI", subTopic: "MLOps", system: "Prediction", symptom: "Accuracy dropped 30% in 2 months.", chaosFactor: "Training data was winter; now it is summer.", solutionClues: ["Retraining", "Monitoring"], level: "Senior" },
  { title: "Vector Clash", category: "AI", subTopic: "RAG", system: "Pinecone", symptom: "Search returns 0 results for exact matches.", chaosFactor: "Embedding model mismatch between index/query.", solutionClues: ["Consistency", "Normalizing"], level: "Senior" },
  { title: "Hallucination Loop", category: "AI", subTopic: "Agent", system: "Chain", symptom: "Agent repeats same wrong step.", chaosFactor: "No termination condition in ReAct loop.", solutionClues: ["Stop sequences", "Max iterations"], level: "Senior" },
  { title: "Prompt Injection", category: "AI", subTopic: "Security", system: "LLM", symptom: "Agent reveals internal API keys.", chaosFactor: "User bypassed system prompt via 'Ignore prev'.", solutionClues: ["Input filters", "Guardrails"], level: "Senior" },
  { title: "Training Leakage", category: "AI", subTopic: "ML", system: "Dataset", symptom: "100% accuracy on test, 40% on prod.", chaosFactor: "Test data accidentally included in training set.", solutionClues: ["Data splitting", "Validation"], level: "Senior" },
  { title: "Cold Storage Lag", category: "AI", subTopic: "Data", system: "S3", symptom: "Reports take 15 minutes to run.", chaosFactor: "Querying raw CSVs instead of Parquet.", solutionClues: ["Parquet", "Athena/S3 Select"], level: "Senior" },
  { title: "Feature Inconsistency", category: "AI", subTopic: "Data", system: "Pipeline", symptom: "Model predicts 'NaN' for new users.", chaosFactor: "Feature engineering logic differs in Prod vs Research.", solutionClues: ["Feature Store", "Shared library"], level: "Senior" },
  { title: "PII Leakage", category: "AI", subTopic: "Privacy", system: "Dataset", symptom: "LLM quotes real customer credit cards.", chaosFactor: "Training data not scrubbed of sensitive info.", solutionClues: ["Anonymization", "DP"], level: "Senior" },
  { title: "Bias Skew", category: "AI", subTopic: "Ethics", system: "Model", symptom: "Approval rates differ by demographic.", chaosFactor: "Under-representation in training samples.", solutionClues: ["Over-sampling", "Bias audit"], level: "Senior" }
 
];